### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by anandkolli** [gfleury/tsuru-helm-chart#1]
Hello,

Thank you for providing helm files for the installation of tsuru.

I have installed kubernetes cluster using minikube and when I tried installing tsuru using helm,
I am getting an error as shown below.

root@helm-virtual-machine:~# helm install --name my-release tsuru-helm-chart
Error: found in requirements.yaml, but missing in charts/ directory: nginx-ingress, mongodb-replicaset, docker-registry, kube-lego

and on the second attempt I removed the requirements.yaml file from folder tsuru-helm-chart and tried then the deployment started on kubernetes cluster but one of the pods was failing.
root@helm-virtual-machine:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                  READY     STATUS             RESTARTS   AGE
default       my-release-tsuru-5c49b47878-zx8d8                     0/1       CrashLoopBackOff   4          2m
default       my-release-tsuru-docker-builder-7b77cbd65c-986ts      2/2       Running            1          2m
default       my-release-tsuru-gandalf-68f8d9df77-c9bqq             1/1       Running            0          2m
default       my-release-tsuru-kubernetes-router-8664957cc9-499z8   1/1       Running            0          2m
kube-system   kube-addon-manager-minikube                           1/1       Running            0          36m
kube-system   kube-dns-86f6f55dd5-fvf5w                             3/3       Running            0          36m
kube-system   kubernetes-dashboard-d94zk                            1/1       Running            0          36m
kube-system   storage-provisioner                                   1/1       Running            0          36m
kube-system   tiller-deploy-7777bff5d-5pt2s                         1/1       Running            0          33m

Any help will be appreciated.

Thanks,
Anand

**Comment by gfleury** [comment]
Hi, thanks for the feedback, after cloning the repository try to run, 

helm dep up tsuru-helm-chart

This error is probably because isn't installing all the necessary dependent charts. 

Let me know if it work for you.

**Comment by anandkolli** [comment]
Thank you for the quick response and it worked partially, i.e. nginx-ingress-controller pod was crashing and did not came up.

And also issue while connecting to tsuru server

root@helm-virtual-machine:~# tsuru login admin@example.com
Password: Error: Failed to connect to tsuru server (http://tsuru.local), it's probably down.

root@helm-virtual-machine:~/tapp# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                        READY     STATUS             RESTARTS   AGE
default       my-release-docker-registry-6dbf58879c-m65zs                 1/1       Running            0          14m
default       my-release-kube-lego-8b697858-k8tzz                         1/1       Running            0          14m
default       my-release-mongodb-replicaset-0                             1/1       Running            0          14m
default       my-release-mongodb-replicaset-1                             1/1       Running            0          8m
default       my-release-mongodb-replicaset-2                             1/1       Running            0          8m
default       my-release-nginx-ingress-controller-56bd56cbff-qdpr2        0/1       **CrashLoopBackOff**   7          14m
default       my-release-nginx-ingress-default-backend-65dc9dc4bd-56nt9   1/1       Running            0          14m
default       my-release-tsuru-5c49b47878-lvmc5                           1/1       Running            4          14m
default       my-release-tsuru-docker-builder-7b77cbd65c-wjqmc            2/2       Running            1          14m
default       my-release-tsuru-gandalf-68f8d9df77-v2pwk                   1/1       Running            0          14m
default       my-release-tsuru-kubernetes-router-8664957cc9-bqbz7         1/1       Running            0          14m
kube-system   kube-addon-manager-minikube                                 1/1       Running            0          18m
kube-system   kube-dns-86f6f55dd5-xt5ll                                   3/3       Running            0          18m
kube-system   kubernetes-dashboard-mdkrf                                  1/1       Running            0          18m
kube-system   storage-provisioner                                         1/1       Running            0          18m
kube-system   tiller-deploy-7777bff5d-m4n92                               1/1       Running            0          14m

One of the pod was failing and below are the logs of that pod
root@helm-virtual-machine:~/tapp# kubectl logs --tail=30 my-release-nginx-ingress-controller-56bd56cbff-qdpr2
I0117 11:28:28.979523       7 launch.go:113] &{NGINX 0.9.0-beta.15 git-a3e86f2 https://github.com/kubernetes/ingress}
I0117 11:28:28.979887       7 launch.go:116] Watching for ingress class: nginx
I0117 11:28:28.980218       7 launch.go:291] Creating API client for https://10.96.0.1:443
I0117 11:28:28.998769       7 launch.go:304] Running in Kubernetes Cluster version v1.8 (v1.8.0) - git (clean) commit 0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4 - platform linux/amd64
I0117 11:28:29.007165       7 launch.go:140] validated default/my-release-nginx-ingress-default-backend as the default backend
F0117 11:28:29.011679       7 launch.go:158] service default/my-release-nginx-ingress-controller does not (yet) have ingress points

Thanks,
Anand

**Comment by gfleury** [comment]
Usually it could take a while to get everything up.
Regarding, 

```
# tsuru login.... 
```

on the target tsuru.local, how are you managing DNS on this example? tsuru.local does you have it pointing to the main ingress router? as you are using minikube, I'm not sure how it would work. I will have to test it. I'm always using direct on AWS resources, so I always point the dns to the main ELB that 'route' everything into the main nginx ingress controller. 

First step, could you check again if nginx-ingress-controller is running or if it still crashing? 

Thanks, looking forward to hear from you.

**Comment by harshapic** [comment]
I am also facing same issue: (even upgraded ingress to quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0 in values.yaml file)
kubectl get pods
NAME                                                         READY     STATUS             RESTARTS   AGE
my-release3-docker-registry-769b96c466-zbvtw                 1/1       Running            0          8m
my-release3-kube-lego-6bdcf75c79-brb5b                       1/1       Running            0          8m
my-release3-mongodb-replicaset-0                             1/1       Running            0          8m
my-release3-mongodb-replicaset-1                             1/1       Running            0          8m
my-release3-mongodb-replicaset-2                             1/1       Running            0          7m
my-release3-nginx-ingress-controller-c7955d684-dbfbb         0/1       CrashLoopBackOff   6          8m
my-release3-nginx-ingress-default-backend-5f84f56cb9-rbdbc   1/1       Running            0          8m
my-release3-tsuru-6947c65766-klbmf                           1/1       Running            0          8m
my-release3-tsuru-docker-builder-6dcbd6f466-h29dm            2/2       Running            1          8m
my-release3-tsuru-gandalf-6f69d9765b-xj2pd                   1/1       Running            0          8m
my-release3-tsuru-kubernetes-router-85996dc74d-b6h6h         1/1       Running            0          8m

Logs of ingress pod:
 kubectl logs  my-release3-nginx-ingress-controller-c7955d684-dbfbb
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.9.0
  Build:      git-6816630
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------

I0130 10:48:37.626789       9 flags.go:151] Watching for ingress class: nginx
I0130 10:48:37.632593       9 main.go:227] Creating API client for https://10.96.0.1:443
I0130 10:48:37.649363       9 main.go:239] Running in Kubernetes Cluster version v1.8 (v1.8.0) - git (clean) commit 0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4 - platform linux/amd64
I0130 10:48:37.653287       9 main.go:83] validated default/my-release3-nginx-ingress-default-backend as the default backend
F0130 10:48:37.657766       9 main.go:101] service default/my-release3-nginx-ingress-controller does not (yet) have ingress points

**Comment by harshapic** [comment]
I am running this minikube on vmware ubuntu machine locally on my laptop. It seems "nginx-ingress-controller" service is not able to get external-ip, how can i point to nodeport instead of external-ip

**Comment by gfleury** [comment]
@harshapic Let me test it with minikube, never used it with minikube, I will keep you posted.

**Comment by harshapic** [comment]
On minikube use kubernetes version v1.8.0...with tsuru there is issue with v1.9.0 kubernetes version.
Instead ingress router why cant you use default planb router itslef?

**Comment by gfleury** [comment]
nginx-ingress has others features like ACME/lets encrypt and support other services that you can deploy outside of tsuru (direct on kubernetes). Planb will work only with tsuru itself. I will take a look.

**Comment by gfleury** [comment]
Hi guys, I've got everything running (all pods) on minikube by changing some values on values.yaml

It's available on branch [minikube](/gfleury/tsuru-helm-chart/tree/minikube)

But I still didn't get to login on tsuru, I didn't had time today. I will continue tomorrow. But is just a matter of disabling publish-service tag on nginx-ingress and change from LoadBalancer to NodePort as @harshapic  said before.

**Comment by gfleury** [comment]
Actually, I've tried and worked perfectly, 

[root@Minikube tsuru-client]# ./bin/tsuru target-add default http://tsuru.local:32080/
New target default -> http://tsuru.local:32080/ added to target list
[root@Minikube tsuru-client]# ./bin/tsuru target-set default
New target is default -> http://tsuru.local:32080/
[root@Minikube tsuru-client]# ./bin/tsuru login admin@example.com
Password: 
Successfully logged in!



The only detail is that I've used my local dns pointing to a local dnsmasq that had one line entry like:

address=/local/192.168.39.98


where 192.168.39.98 is the ip of my minikube vm. As we changed LoadBalancer to NodePort (32080), just use all http traffic to port 32080, this why  http://tsuru.local:32080/

Let me know if it work for you.

**Comment by harshapic** [comment]
As you suggested i switched to minkube branch now all pods are running but when i trying to create admin user its giving me error:

export POD_NAME=$(kubectl get pods --namespace default -l "app=tsuru,release=my-release5" -o jsonpath="{.items[0].metadata.name}")
root@kube-sat:~# kubectl exec -it $POD_NAME tsurud root-user-create admin@example.com
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
Password: 
Confirm: 
Error: Failed to connect to MongoDB of Gandalf "my-release5-mongodb-replicaset:27017" - no reachable servers.
command terminated with exit code 1

**Comment by gfleury** [comment]
Creating admin user is Step 3, did the command on step 2 ran ok?

"2. Update gandalf configMap TSURU_TOKEN"

**Comment by harshapic** [comment]
yes it ran fine.Its giving only error at 3rd step.
error:

root@kube-sat:~# kubectl get services my-release9-nginx-ingress-controller -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
root@kube-sat:~# export LB_HOSTNAME=tsuru.local
root@kube-sat:~# echo $LB_HOSTNAME
tsuru.local
root@kube-sat:~# kubectl get pods --namespace default -l "app=tsuru,release=my-release9" -o jsonpath="{.items[0].metadata.name}"
my-release9-tsuru-6dcbdc69d-mklqgroot@kube-sat:~# export POD_NAME=$(kubectl get pods --namespace default -l "app=tsuru,release=my-release9" -o jsonpath="{.items[0].metadata.name}")
root@kube-sat:~# kubectl patch configmap my-release9-tsuru-gandalf-env-var -p "{\"data\":{\"TSURU_TOKEN\":\"$(kubectl exec $POD_NAME tsurud token)\"}}"
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
configmap "my-release9-tsuru-gandalf-env-var" patched
root@kube-sat:~# kubectl delete pod $(kubectl get pods --namespace default -l "app=tsuru-gandalf,release=my-release9" -o jsonpath="{.items[0].metadata.name}")
pod "my-release9-tsuru-gandalf-fbd5b7c66-bprvt" deleted
root@kube-sat:~# export POD_NAME=$(kubectl get pods --namespace default -l "app=tsuru,release=my-release9" -o jsonpath="{.items[0].metadata.name}")
root@kube-sat:~# kubectl exec -it $POD_NAME tsurud root-user-create admin@example.com
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
Password: 
Confirm: 
Error: Failed to connect to MongoDB of Gandalf "my-release9-mongodb-replicaset:27017" - no reachable servers.
command terminated with exit code 1

**Comment by gfleury** [comment]
Oh, try to run it again. After you ran the second step the gandalf will be recreated, so it could take a while. Try to run the step 3 again and check if all PODs are running ok.

**Comment by harshapic** [comment]
Thanks it worked.
But after setting up tsuru client there were no nodes, i am trying to add nodes in tsuru nut it always says waiting:(my minikube ip is 192.168.99.101)

tsuru node-add docker pool=theonepool --register address=http://192.168.99.101:2375
Node successfully registered.
root@kube-sat:~/.minikube/machines/minikube# tsuru node-update http://192.168.99.101:2375 --enable
Node successfully updated.
root@kube-sat:~/.minikube/machines/minikube# tsuru node list
+----------------------------+---------+---------+-----------------+
| Address                    | IaaS ID | Status  | Metadata        |
+----------------------------+---------+---------+-----------------+
| http://192.168.99.101:2375 |         | waiting | iaas-id=        |
|                            |         |         | pool=theonepool |

**Comment by gfleury** [comment]
Try to add a new platform. This need at least one docker node working on tsuru. 

# tsuru -v 2 platform-add python

**Comment by gfleury** [comment]
Actually, one detail, don't add the docker from the minikube machine, there is a pod running similar to a sidecar only to allow buildings, there is a pull request ongoing to allow native buildings with kubernetes on Tsuru. 

add a node like, 

address=http://my-release9-tsuru-docker-builder:2375

**Comment by harshapic** [comment]
Added node, trying to create app, its giving error:

tsuru app-create tsuru-dashboard python --pool=theonepool
Error: tsuru failed to create the app "tsuru-dashboard": Could not create git bare repository: exit status 128. fatal: cannot mkdir /var/lib/gandalf/repositories/tsuru-dashboard.git: Permission denied

**Comment by gfleury** [comment]
I will check gandalf, I'm not using it here, but I will check. 

another extra, after adding, you can add the kubernetes itself as a cluster into tsuru with, 

```
# tsuru cluster-add default kubernetes --addr https://kubernetes --default --cacert ~/.minikube/ca.crt --clientkey /root/.minikube/client.key --clientcert  /root/.minikube/client.crt
# tsuru node-list
+---------------------------------------+---------+--------+-------------------------------------------------------------+
| Address                               | IaaS ID | Status | Metadata                                                    |
+---------------------------------------+---------+--------+-------------------------------------------------------------+
| 192.168.39.98                         |         | Ready  | alpha.kubernetes.io/provided-node-ip=192.168.39.98          |
|                                       |         |        | beta.kubernetes.io/arch=amd64                               |
|                                       |         |        | beta.kubernetes.io/os=linux                                 |
|                                       |         |        | kubernetes.io/hostname=minikube                             |
|                                       |         |        | node.alpha.kubernetes.io/ttl=0                              |
|                                       |         |        | tsuru.io/cluster=default                                    |
|                                       |         |        | volumes.kubernetes.io/controller-managed-attach-detach=true |
+---------------------------------------+---------+--------+-------------------------------------------------------------+
| http://test-tsuru-docker-builder:2375 |         | ready  | LastSuccess=2018-01-30T22:16:25Z                            |
|                                       |         |        | pool=builder                                                |
+---------------------------------------+---------+--------+-------------------------------------------------------------+

```

**Comment by gfleury** [comment]
@harshapic Hey, I've commited some changes on the minikube branch, I was able to create the application and so on. Just heads on that the git hook isn't working properly, but you can deploy using all the other methods (image or source code directly). Can you pull it and tell me if it worked? 
thanks for testing.

**Comment by harshapic** [comment]
Thanks @gfleury, i will check and let you know. This helped me a lot.
